# SonarQube Configuration
sonar.projectKey=validation
sonar.projectName=Validation Service
sonar.projectVersion=1.0
sonar.sources=src/main/java
sonar.java.binaries=target/classes
sonar.java.source=21
sonar.java.target=21
sonar.sourceEncoding=UTF-8
# SonarQube Server Configuration
sonar.host.url=https://sonar.promixhub.com
sonar.token=squ_8de7e7bfdabc53cfbcf51553595f5c281c840c35